// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpecPattern.Infrastructure.Data;

namespace SpecPattern.Infrastructure.Migrations
{
    [DbContext(typeof(DbSpecPattern))]
    [Migration("20201123175413_Created-table-director")]
    partial class Createdtabledirector
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SpecPattern.Domain.Entities.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_director");

                    b.ToTable("director");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Marc Webb"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bill Condon"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chris Renaud"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Jon Favreau"
                        },
                        new
                        {
                            Id = 5,
                            Name = "M. Night Shyamalan"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Alex Kurtzman"
                        });
                });

            modelBuilder.Entity("SpecPattern.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DirectorId")
                        .HasColumnName("director_id")
                        .HasColumnType("integer");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnName("genre")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int>("MpaaRating")
                        .HasColumnName("mpaa_rating")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<double>("Rating")
                        .HasColumnName("rating")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnName("release_date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id")
                        .HasName("pk_movies");

                    b.HasIndex("DirectorId")
                        .HasName("ix_movies_director_id");

                    b.ToTable("movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DirectorId = 1,
                            Genre = "Adventure",
                            MpaaRating = 3,
                            Name = "The Amazing Spider-Man",
                            Rating = 7.0,
                            ReleaseDate = new DateTime(2019, 11, 23, 18, 54, 12, 435, DateTimeKind.Local).AddTicks(967)
                        },
                        new
                        {
                            Id = 2,
                            DirectorId = 2,
                            Genre = "Family",
                            MpaaRating = 3,
                            Name = "Beauty and the Beast",
                            Rating = 7.7999999999999998,
                            ReleaseDate = new DateTime(2018, 11, 23, 18, 54, 12, 443, DateTimeKind.Local).AddTicks(9464)
                        },
                        new
                        {
                            Id = 3,
                            DirectorId = 3,
                            Genre = "Adventure",
                            MpaaRating = 1,
                            Name = "The Secret Life of Pets",
                            Rating = 9.0,
                            ReleaseDate = new DateTime(2017, 11, 23, 18, 54, 12, 443, DateTimeKind.Local).AddTicks(9572)
                        },
                        new
                        {
                            Id = 4,
                            DirectorId = 4,
                            Genre = "Fantasy",
                            MpaaRating = 2,
                            Name = "The Jungle Book",
                            Rating = 7.9000000000000004,
                            ReleaseDate = new DateTime(2019, 11, 23, 18, 54, 12, 443, DateTimeKind.Local).AddTicks(9591)
                        },
                        new
                        {
                            Id = 5,
                            DirectorId = 5,
                            Genre = "Horror",
                            MpaaRating = 3,
                            Name = "Split",
                            Rating = 6.5,
                            ReleaseDate = new DateTime(2015, 11, 23, 18, 54, 12, 443, DateTimeKind.Local).AddTicks(9604)
                        },
                        new
                        {
                            Id = 6,
                            DirectorId = 6,
                            Genre = "Action",
                            MpaaRating = 4,
                            Name = "The Mummy",
                            Rating = 8.9000000000000004,
                            ReleaseDate = new DateTime(2020, 11, 23, 18, 54, 12, 443, DateTimeKind.Local).AddTicks(9614)
                        });
                });

            modelBuilder.Entity("SpecPattern.Domain.Entities.Movie", b =>
                {
                    b.HasOne("SpecPattern.Domain.Entities.Director", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorId")
                        .HasConstraintName("fk_movies_director_director_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
